cameras:
  - stream_id: stream
    passthrough: false        # If the stream should be passed through without geo mapping (all other parameters are ignored if true)
    focallength_mm: 20        # view_*_deg and image dimensions are equivalent. Sensor size is harder to obtain and therefore only second choice.
    sensor_height_mm: 16      # See above
    sensor_width_mm: 9        # See above
    view_x_deg: 90
    view_y_deg: 54
    image_width_px: 1920
    image_height_px: 1080
    elevation_m: 10
    tilt_deg: 45              # 0° = camera facing straight down (image plane parallel to the ground), 90° camera pointed at horizon (image plane 90° to the ground)
    pos_lat: 52
    pos_lon: 10
    heading_deg: 90
    abc_distortion_a: 0
    abc_distortion_b: 0
    abc_distortion_c: 0

log_level: DEBUG
redis:
  host: redis
  port: 6379