cameras:
  - stream_id: stream
    focallength_mm: 20
    sensor_height_mm: 16
    sensor_width_mm: 9
    view_x_deg: 90
    view_y_deg: 54
    image_width_px: 1920
    image_height_px: 1080
    elevation_m: 10
    tilt_deg: 45
    pos_lat: 52
    pos_lon: 10
    heading_deg: 90
    abc_distortion_a: 0
    abc_distortion_b: 0
    abc_distortion_c: 0

log_level: DEBUG
redis:
  host: redis
  port: 6379