cameras:
  - stream_id: stream1
    cam_config_path: None
    mapping_area:               # Must be a geojson `Polygon`. If set, only detections within that polygon will be mapped (i.e. will have coordinates set)
      type: Polygon
      coordinates: [[           # [lon, lat] format. The last point must equal the first!
          [10, 50],
        ]]
    remove_unmapped_detections: false # If unmapped detections should be removed (i.e. detections filtered by mapping_area, see above)

  -stream_id: stream2
    cam_config_path: None
    mapping_area:               # Must be a geojson `Polygon`. If set, only detections within that polygon will be mapped (i.e. will have coordinates set)
      type: Polygon
      coordinates: [[           # [lon, lat] format. The last point must equal the first!
          [10, 50],
        ]]
    remove_unmapped_detections: false # If unmapped detections should be removed (i.e. detections filtered by mapping_area, see above)


object_center_elevation_m: 0 

log_level: DEBUG
redis:
  host: localhost
  port: 6379