cameras:
  stream_id: stream
  focallength_mm: 20
  sensor_height_mm: 16
  sensor_width_mm: 9
  image_width_px: 1920
  image_height_px: 1080
  elevation_m: 10
  tilt_deg: 45
  pos_lat: 52
  pos_lon: 10
  heading_deg: 90

log_level: DEBUG
redis:
  host: redis
  port: 6379